title: My Systems Development Blog
author: Erik Donovan
email: erik@jetpropilots.com
description: > # this means to ignore newlines until "baseurl:"
  A systems developer is a type of software developer. They develop and implement 
  applications and programs for the backend processing systems used in businesses 
  and organisations. Backend processing systems are the behind-the-scenes parts of 
  software that don’t have a user interface, except for administration purposes. 
  
# social links
twitter_username: devsmasher # DO NOT include the @ character, or else the build will fail!
github_username:  devsmasher # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
